'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Proveedor_Contactos
    Public Property ProveContactoID As Integer
    Public Property ProveedorID As Integer
    Public Property ProveedorContacto As String
    Public Property ProveedorContactoCorreo As String

    Public Overridable Property GIC_Proveedor As GIC_Proveedor

End Class
