'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Proveedor_CuentasCorrientes
    Public Property ProveCuCoID As Integer
    Public Property ProveedorID As Integer
    Public Property BancoID As Integer
    Public Property ProveedorCuentasCorrientes As String

    Public Overridable Property GIC_Banco As GIC_Banco
    Public Overridable Property GIC_Proveedor As GIC_Proveedor

End Class
