'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_CuentasContable
    Public Property CuentaContaID As Integer
    Public Property CuentaContaDescripcion As String
    Public Property Activo As Short

    Public Overridable Property GIC_SubCuentas As ICollection(Of GIC_SubCuentas) = New HashSet(Of GIC_SubCuentas)
    Public Overridable Property GIC_FondoPorRendir As ICollection(Of GIC_FondoPorRendir) = New HashSet(Of GIC_FondoPorRendir)

End Class
