'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_EstadosFondoPorRendir
    Public Property EstadoFPRID As Integer
    Public Property EstadosFondoPorRendir As String
    Public Property EstadosFondoObservacion As String

    Public Overridable Property GIC_FondoPorRendir As ICollection(Of GIC_FondoPorRendir) = New HashSet(Of GIC_FondoPorRendir)

End Class
