'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FondoPorRendirTareas
    Public Property FPRTareasID As Integer
    Public Property FPRTareasDescripcion As String

    Public Overridable Property GIC_FondoPorRendirDetalle As ICollection(Of GIC_FondoPorRendirDetalle) = New HashSet(Of GIC_FondoPorRendirDetalle)

End Class
