'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_SubCuentas
    Public Property SubCuentaID As Integer
    Public Property CuentaContaID As Integer
    Public Property SubCuentaNumero As Integer
    Public Property SubCuentaNombre As String
    Public Property SubCuentaDescripcion As String
    Public Property SubCuentaFechaIng As Date
    Public Property ClienteID As Integer
    Public Property SubCuentaOfertaRefID As Integer
    Public Property SubCuentaEstado As Integer
    Public Property SubCuentasGradoID As Integer
    Public Property UsuarioID As Integer
    Public Property Activo As Boolean

    Public Overridable Property GIC_Cliente As GIC_Cliente
    Public Overridable Property GIC_CuentasContable As GIC_CuentasContable
    Public Overridable Property GIC_FondoPorRendir As ICollection(Of GIC_FondoPorRendir) = New HashSet(Of GIC_FondoPorRendir)
    Public Overridable Property GIC_SubCuentasGradoSatisfaccion As GIC_SubCuentasGradoSatisfaccion
    Public Overridable Property GIC_SubCuentasDetalle As ICollection(Of GIC_SubCuentasDetalle) = New HashSet(Of GIC_SubCuentasDetalle)

End Class
