'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_TipoEmpresa
    Public Property TipoEmpID As Integer
    Public Property TipoEmpresaNombre As String
    Public Property Activo As Nullable(Of Integer)

    Public Overridable Property GIC_Cliente As ICollection(Of GIC_Cliente) = New HashSet(Of GIC_Cliente)

End Class
