'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Banco
    Public Property BancoID As Integer
    Public Property BancoNombre As String
    Public Property Activo As Nullable(Of Integer)

    Public Overridable Property GIC_FichaPersonal As ICollection(Of GIC_FichaPersonal) = New HashSet(Of GIC_FichaPersonal)
    Public Overridable Property GIC_FichaPersonal_CuentasCorrientes As ICollection(Of GIC_FichaPersonal_CuentasCorrientes) = New HashSet(Of GIC_FichaPersonal_CuentasCorrientes)
    Public Overridable Property GIC_Proveedor_CuentasCorrientes As ICollection(Of GIC_Proveedor_CuentasCorrientes) = New HashSet(Of GIC_Proveedor_CuentasCorrientes)

End Class
