'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_AreaTrabajo
    Public Property AreaTrabID As Integer
    Public Property AreaTrabNombre As String
    Public Property Activo As Nullable(Of Integer)

    Public Overridable Property GIC_FichaPersonal As ICollection(Of GIC_FichaPersonal) = New HashSet(Of GIC_FichaPersonal)

End Class
