'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Region
    Public Property RegionID As Integer
    Public Property Region_numero_romano As String
    Public Property RegionNombre As String
    Public Property Capital As String
    Public Property Activo As Nullable(Of Integer)
    Public Property PaisID As Nullable(Of Integer)

    Public Overridable Property GIC_Pais As GIC_Pais
    Public Overridable Property GIC_Provincia As ICollection(Of GIC_Provincia) = New HashSet(Of GIC_Provincia)

End Class
