'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GICont2015Entities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GICont2015Entities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property GIC_AFP() As DbSet(Of GIC_AFP)
    Public Property GIC_AreaTrabajo() As DbSet(Of GIC_AreaTrabajo)
    Public Property GIC_Banco() As DbSet(Of GIC_Banco)
    Public Property GIC_Cliente() As DbSet(Of GIC_Cliente)
    Public Property GIC_Comuna() As DbSet(Of GIC_Comuna)
    Public Property GIC_CuentasContable() As DbSet(Of GIC_CuentasContable)
    Public Property GIC_EstadosFondoPorRendir() As DbSet(Of GIC_EstadosFondoPorRendir)
    Public Property GIC_FichaPersonal() As DbSet(Of GIC_FichaPersonal)
    Public Property GIC_FichaPersonal_CuentasCorrientes() As DbSet(Of GIC_FichaPersonal_CuentasCorrientes)
    Public Property GIC_FichaPersonal_Documentos() As DbSet(Of GIC_FichaPersonal_Documentos)
    Public Property GIC_FichaPersonalHistorico() As DbSet(Of GIC_FichaPersonalHistorico)
    Public Property GIC_FondoPorRendir() As DbSet(Of GIC_FondoPorRendir)
    Public Property GIC_FondoPorRendirDetalle() As DbSet(Of GIC_FondoPorRendirDetalle)
    Public Property GIC_FondoPorRendirImagenRendicionExt() As DbSet(Of GIC_FondoPorRendirImagenRendicionExt)
    Public Property GIC_FondoPorRendirTareas() As DbSet(Of GIC_FondoPorRendirTareas)
    Public Property GIC_FormaDePago() As DbSet(Of GIC_FormaDePago)
    Public Property GIC_FormaDePagoProveedor() As DbSet(Of GIC_FormaDePagoProveedor)
    Public Property GIC_Giro() As DbSet(Of GIC_Giro)
    Public Property GIC_LogErrores() As DbSet(Of GIC_LogErrores)
    Public Property GIC_Pais() As DbSet(Of GIC_Pais)
    Public Property GIC_Proveedor() As DbSet(Of GIC_Proveedor)
    Public Property GIC_Proveedor_Contactos() As DbSet(Of GIC_Proveedor_Contactos)
    Public Property GIC_Proveedor_CuentasCorrientes() As DbSet(Of GIC_Proveedor_CuentasCorrientes)
    Public Property GIC_Provincia() As DbSet(Of GIC_Provincia)
    Public Property GIC_Region() As DbSet(Of GIC_Region)
    Public Property GIC_Salud() As DbSet(Of GIC_Salud)
    Public Property GIC_SubCuentas() As DbSet(Of GIC_SubCuentas)
    Public Property GIC_SubCuentasDetalle() As DbSet(Of GIC_SubCuentasDetalle)
    Public Property GIC_SubCuentasGradoSatisfaccion() As DbSet(Of GIC_SubCuentasGradoSatisfaccion)
    Public Property GIC_TipoDocumento() As DbSet(Of GIC_TipoDocumento)
    Public Property GIC_TipoEmpresa() As DbSet(Of GIC_TipoEmpresa)
    Public Property GIC_TipoProveedor() As DbSet(Of GIC_TipoProveedor)
    Public Property GIC_Usuarios() As DbSet(Of GIC_Usuarios)
    Public Property sysdiagrams() As DbSet(Of sysdiagrams)

End Class
