Public Class TipoErrorValidacion

    Public Const RUT_VACIO As String = "Rut Vacio ,Favor ingrese Rut Correctamente"
    Public Const NOM_VACIO As String = "Nombre Vacio ,Favor ingrese nombre Correctamente"
    Public Const CORREO_VACIO As String = "Correo Vacio ,Favor ingrese correo Correctamente"
    Public Const DIRECCION_VACIO As String = "Direccion Vacia ,Favor ingrese direccion Correctamente"
    Public Const FONO_VACIO As String = "Telefono Vacio ,Favor ingrese telefono Correctamente"
    Public Const CELULAR_VACIO As String = "Celular Vacio ,Favor ingrese celular Correctamente"
    Public Const COMUNA_VACIO As String = "Seleccione una Comuna Correctamente"
    Public Const CIUDAD_VACIO As String = "Seleccione una Ciudad Correctamente"
    Public Const GIRO_VACIO As String = "Seleccione un Giro Correctamente"
    Public Const FAX_VACIO As String = "Fax Vacio ,Favor ingrese fax Correctamente"
    Public Const SITIO_VACIO As String = "Sitio Vacio ,Favor ingrese Sitio Correctamente"
    Public Const OTROS_VACIO As String = "Sitio Vacio ,Favor ingrese Otros Correctamente"
    Public Const LOGO_VACIO As String = "Logo Vacio ,Favor ingrese Logo Correctamente"
    Public Const TAMANO_VACIO As String = "Seleccione un Tamaño Empresa Correctamente"
    Public Const TIPOEMPRESA_VACIO As String = "Seleccione un Tipo Empresa Correctamente"
    Public Const FECHA_INGRESO_VACIO As String = "Fecha ingreso vacia ,Favor ingresar  Correctamente"
    Public Const FECHA_NACI_VACIO As String = "Fecha nacimiento vacia ,Favor ingresar Correctamente"
    Public Const EDAD_VACIO As String = "Fecha ingreso vacia ,Favor  Correctamente"
    Public Const NACIONAL_VACIO As String = "Nacionalidad vacia ,Favor  Correctamente"
    Public Const ESTUDIOS_VACIO As String = "Estudios vacios ,Favor  Correctamente"
    Public Const FONO_CASA_VACIO As String = "Estudios vacios ,Favor  Correctamente"
    Public Const AFP_VACIO As String = "Seleccione una AFP Correctamente"
    Public Const BANCO_VACIO As String = "Seleccione un Banco Correctamente"
    Public Const RECOMENDAR_VACIO As String = "Recomendación vacia ,Favor  Correctamente"
    Public Const FECHA_INI_CONTRATO_VACIO As String = "Fecha inicio contrato vacia ,Favor  Correctamente"
    Public Const FECHA_FIN_CONTRATO_VACIO As String = "Fecha fin contrato vacia ,Favor  Correctamente"
    Public Const AREA_VACIO As String = "Seleccione un Area Trabajador Correctamente"
    Public Const SALUD_VACIO As String = "Seleccione un tipo salud Trabajador Correctamente"
    Public Const ESTADO_VACIO As String = "Seleccione un estado Correctamente"
    Public Const RAZON_VACIO As String = "Razon social vacia ,Favor  Correctamente"
    Public Const TIPO_PROVEE_VACIO As String = "Seleccione un tipo proveedor Correctamente"
End Class
