'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FichaPersonalHistorico
    Public Property FichaPersonalHistoricoID As Integer
    Public Property FechaIngresoHistorico As Nullable(Of Date)
    Public Property FichaPersonalID As Integer
    Public Property FichaPersonalNombre As String
    Public Property FichaPersonalRUT As String
    Public Property FichaPersonalFechaNac As Nullable(Of Date)
    Public Property FichaPersonalEdad As Nullable(Of Integer)
    Public Property FichaPersonalEstCivil As Nullable(Of Integer)
    Public Property FichaPersonalNacionalidad As String
    Public Property FichaPersonalDireccion As String
    Public Property ComunaID As Integer
    Public Property CiudadID As Integer
    Public Property FichaPersonalEstudios As String
    Public Property FichaPersonalTelefono As String
    Public Property FichaPersonalCelular As String
    Public Property FichaPersonalTelEmerg As String
    Public Property FichaPersonalCorreo As String
    Public Property FichaPersonalLicencia As Nullable(Of Boolean)
    Public Property AfpID As Nullable(Of Integer)
    Public Property Costizacion As Nullable(Of Integer)
    Public Property SaludID As Nullable(Of Integer)
    Public Property CostoIsapre As Nullable(Of Integer)
    Public Property BancoID As Nullable(Of Integer)
    Public Property FichaPersonalCuentaCorriente As String
    Public Property FichaPersonalRecomendado As String
    Public Property Otros As String
    Public Property FechaInicioContrato As Nullable(Of Date)
    Public Property FechaFinContrato As Nullable(Of Date)
    Public Property AreaTrabID As Nullable(Of Integer)
    Public Property Activo As Short
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property SueldoBase As Decimal
    Public Property Colacion As Decimal
    Public Property Prestamos As Decimal
    Public Property Anticipos As Decimal
    Public Property APV As Decimal
    Public Property AhorroVoluntario As Decimal
    Public Property Beneficios As Decimal
    Public Property FotoPersonal As Byte()
    Public Property RutPersonal As Byte()
    Public Property FirmaPersonal As Byte()
    Public Property UsuarioID As Integer

End Class
