'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_SubCuentasDetalle
    Public Property SubCuentaDetalleID As Integer
    Public Property SubCuentaID As Integer
    Public Property NumeroEEPP As Integer
    Public Property DescripcionEstadoPago As String
    Public Property FechaEEPP As Date
    Public Property MonedaEEPP As Decimal
    Public Property MontoEEPP As Decimal
    Public Property ImpuestoEEPP As Decimal
    Public Property TotalEEPP As Decimal

    Public Overridable Property GIC_SubCuentas As GIC_SubCuentas

End Class
