'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FichaPersonal_Documentos
    Public Property FichaPersonalDoc As Integer
    Public Property FichaPersonalID As Integer
    Public Property FichaPersonalDocumento As Byte()
    Public Property FichaPersonalDescripcion As String

    Public Overridable Property GIC_FichaPersonal As GIC_FichaPersonal

End Class
