'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FichaPersonal_CuentasCorrientes
    Public Property PersonalCuCoID As Integer
    Public Property FichaPersonalID As Integer
    Public Property BancoID As Integer
    Public Property PersonalCuentasCorrientes As String

    Public Overridable Property GIC_FichaPersonal As GIC_FichaPersonal

End Class
