'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Proveedor
    Public Property ProveedorID As Integer
    Public Property ProveedorDesc As String
    Public Property ProveedorRUT As String
    Public Property ProveedorDireccion As String
    Public Property ComunaID As Nullable(Of Integer)
    Public Property CiudadID As Nullable(Of Integer)
    Public Property ProveedorContacto As String
    Public Property GiroID As Nullable(Of Integer)
    Public Property ProveedorTelefono As String
    Public Property ProveedorFax As String
    Public Property ProveedorCelular As String
    Public Property ProveedorCorreoElectronico As String
    Public Property ProveedorSitioWeb As String
    Public Property ProveedorApartadoPostal As String
    Public Property Otros As String
    Public Property TipoProveID As Nullable(Of Integer)
    Public Property Logo As Byte()
    Public Property BancoID As Integer
    Public Property ProveedorCuenCorriente As String
    Public Property ProveedorContactos As String
    Public Property Activo As Nullable(Of Short)
    Public Property RegionID As Nullable(Of Integer)
    Public Property FormaDePagoProvID As Integer

    Public Overridable Property GIC_Banco As GIC_Banco
    Public Overridable Property GIC_Ciudad As GIC_Ciudad
    Public Overridable Property GIC_Comuna As GIC_Comuna
    Public Overridable Property GIC_FormaDePagoProveedor As GIC_FormaDePagoProveedor
    Public Overridable Property GIC_Giro As GIC_Giro
    Public Overridable Property GIC_Proveedor_CuentasCorrientes As ICollection(Of GIC_Proveedor_CuentasCorrientes) = New HashSet(Of GIC_Proveedor_CuentasCorrientes)

End Class
