'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Giro
    Public Property GiroID As Integer
    Public Property GiroNombre As String
    Public Property Activo As Nullable(Of Integer)
    Public Property GiroCliente As Nullable(Of Boolean)
    Public Property GiroProveedor As Nullable(Of Boolean)

    Public Overridable Property GIC_Cliente As ICollection(Of GIC_Cliente) = New HashSet(Of GIC_Cliente)
    Public Overridable Property GIC_Proveedor As ICollection(Of GIC_Proveedor) = New HashSet(Of GIC_Proveedor)

End Class
