'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FondoPorRendir
    Public Property FPRID As Integer
    Public Property FichaPersonalID As Integer
    Public Property SubCuentaID As Integer
    Public Property CuentaContaID As Integer
    Public Property FPRMontoAsignado As Decimal
    Public Property FPRDescripcion As String
    Public Property FPRMontoGastado As Decimal
    Public Property FPRSaldoActual As Decimal
    Public Property FPRFechaIngreso As Nullable(Of Date)
    Public Property FPRImagenSolicitud As Byte()
    Public Property FPRImagenTransDestinatario As Byte()
    Public Property FPRImagenRendicion As Byte()
    Public Property FPRImagenTransSaldo As Byte()
    Public Property EstadoFPRID As Integer
    Public Property FPRSubTotal As Decimal
    Public Property FPRTotal As Decimal
    Public Property UsuarioID As Integer

    Public Overridable Property GIC_CuentasContable As GIC_CuentasContable
    Public Overridable Property GIC_EstadosFondoPorRendir As GIC_EstadosFondoPorRendir
    Public Overridable Property GIC_FichaPersonal As GIC_FichaPersonal
    Public Overridable Property GIC_FondoPorRendirDetalle As ICollection(Of GIC_FondoPorRendirDetalle) = New HashSet(Of GIC_FondoPorRendirDetalle)
    Public Overridable Property GIC_FondoPorRendirImagenRendicionExt As ICollection(Of GIC_FondoPorRendirImagenRendicionExt) = New HashSet(Of GIC_FondoPorRendirImagenRendicionExt)
    Public Overridable Property GIC_SubCuentas As GIC_SubCuentas

End Class
