'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Cliente
    Public Property ClienteID As Integer
    Public Property ClienteDesc As String
    Public Property ClienteRUT As String
    Public Property ClienteDireccion As String
    Public Property ComunaID As Integer
    Public Property CiudadID As Integer
    Public Property ClienteContacto As String
    Public Property GiroID As Integer
    Public Property ClienteTelefono As String
    Public Property ClienteFax As String
    Public Property ClienteCelular As String
    Public Property ClienteCorreoElectronico As String
    Public Property ClienteSitioWeb As String
    Public Property ClienteApartadoPostal As String
    Public Property Activo As Short
    Public Property ExcluirDeOportunidades As Nullable(Of Short)
    Public Property RegionID As Nullable(Of Integer)
    Public Property FormaDePagoID As Nullable(Of Integer)
    Public Property Otros As String
    Public Property Logo As Byte()
    Public Property TamanoEmpresa As Nullable(Of Integer)
    Public Property TipoEmpID As Nullable(Of Integer)

    Public Overridable Property GIC_Ciudad As GIC_Ciudad
    Public Overridable Property GIC_Comuna As GIC_Comuna
    Public Overridable Property GIC_Giro As GIC_Giro
    Public Overridable Property GIC_SubCuentas As ICollection(Of GIC_SubCuentas) = New HashSet(Of GIC_SubCuentas)
    Public Overridable Property GIC_FormaDePago As GIC_FormaDePago
    Public Overridable Property GIC_TipoEmpresa As GIC_TipoEmpresa

End Class
