'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FichaPersonal
    Public Property FichaPersonalID As Integer
    Public Property FichaPersonalNombre As String
    Public Property FichaPersonalRUT As String
    Public Property FichaPersonalFechaNac As Nullable(Of Date)
    Public Property FichaPersonalEdad As Nullable(Of Integer)
    Public Property FichaPersonalEstCivil As Nullable(Of Integer)
    Public Property FichaPersonalNacionalidad As String
    Public Property FichaPersonalDireccion As String
    Public Property ComunaID As Integer
    Public Property CiudadID As Integer
    Public Property FichaPersonalEstudios As String
    Public Property FichaPersonalTelefono As String
    Public Property FichaPersonalCelular As String
    Public Property FichaPersonalTelEmerg As String
    Public Property FichaPersonalCorreo As String
    Public Property FichaPersonalLicencia As Nullable(Of Boolean)
    Public Property AfpID As Integer
    Public Property Costizacion As Integer
    Public Property SaludID As Integer
    Public Property CostoIsapre As Integer
    Public Property BancoID As Integer
    Public Property FichaPersonalCuentaCorriente As String
    Public Property FichaPersonalRecomendado As String
    Public Property Otros As String
    Public Property FechaInicioContrato As Date
    Public Property FechaFinContrato As Date
    Public Property AreaTrabID As Integer
    Public Property Activo As Short
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property SueldoBase As Decimal
    Public Property Colacion As Decimal
    Public Property Prestamos As Decimal
    Public Property Anticipos As Decimal
    Public Property APV As Decimal
    Public Property AhorroVoluntario As Decimal
    Public Property Beneficios As Decimal
    Public Property FotoPersonal As Byte()
    Public Property RutPersonal As Byte()
    Public Property FirmaPersonal As Byte()

    Public Overridable Property GIC_AFP As GIC_AFP
    Public Overridable Property GIC_AreaTrabajo As GIC_AreaTrabajo
    Public Overridable Property GIC_Banco As GIC_Banco
    Public Overridable Property GIC_Comuna As GIC_Comuna
    Public Overridable Property GIC_Salud As GIC_Salud
    Public Overridable Property GIC_FichaPersonal_CuentasCorrientes As ICollection(Of GIC_FichaPersonal_CuentasCorrientes) = New HashSet(Of GIC_FichaPersonal_CuentasCorrientes)
    Public Overridable Property GIC_FichaPersonal_Documentos As ICollection(Of GIC_FichaPersonal_Documentos) = New HashSet(Of GIC_FichaPersonal_Documentos)
    Public Overridable Property GIC_FondoPorRendir As ICollection(Of GIC_FondoPorRendir) = New HashSet(Of GIC_FondoPorRendir)

End Class
