'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Provincia
    Public Property ProvinciaID As Integer
    Public Property RegionID As Integer
    Public Property ProvinciaNombre As String
    Public Property Capital As String
    Public Property Activo As Nullable(Of Integer)

    Public Overridable Property GIC_Comuna As ICollection(Of GIC_Comuna) = New HashSet(Of GIC_Comuna)
    Public Overridable Property GIC_Region As GIC_Region

End Class
