'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_FondoPorRendirImagenRendicionExt
    Public Property FPRImgExtID As Integer
    Public Property FPRID As Integer
    Public Property FPRImagenRendicion As Byte()
    Public Property FPRFechaIngreso As Nullable(Of Date)

    Public Overridable Property GIC_FondoPorRendir As GIC_FondoPorRendir

End Class
