'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GIC_Usuarios
    Public Property UsuarioID As Integer
    Public Property Usuario As String
    Public Property UsuarioNombreCompleto As String
    Public Property UsuarioPass As String
    Public Property UsuarioAccesoGrabar As Boolean
    Public Property UsuarioAccesoMod As Boolean
    Public Property UsuarioAccesoDel As Boolean
    Public Property UsuarioAccesoConsultor As Boolean
    Public Property Activo As Short
    Public Property UsuarioFechaIngreso As Nullable(Of Date)

End Class
